package com.myspace.bank_non_delivered_debit;

import com.myspace.bank_non_delivered_debit.Transaction;

rule "All OK"
when
    $t: Transaction( existsInAccount == true, existsInLog == true, matchesValue == true )
then
    modify($t){setOutboundQueue("ALL_OK");}
end

rule "Gabetas OK"
when
    $t: Transaction( existsInAccount == false, existsInLog == true, matchesValue == true )
then
    modify($t){setOutboundQueue("GABETAS");}
end

rule "Gabetas modified "
when
    $t: Transaction( existsInAccount == true, existsInLog == true, matchesValue == false )
then
    modify($t){
        setValue(Math.Abs(valueInAccount - valueInLog));
        setOutboundQueue("ALL_OK");
    }
end