package com.myspace.bank_non_delivered_debit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Client() {
    }




}