package com.myspace.bank_non_delivered_debit;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;
	private java.lang.Integer value;

	private java.lang.Boolean existsInAccount;

	private java.lang.Boolean existsInLog;

	private java.lang.Boolean matchesValue;

	private java.lang.String outboundQueue;

	private java.lang.Integer valueInAccount;

	private java.lang.Integer valueInLog;

	public Transaction() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Integer getValue() {
		return this.value;
	}

	public void setValue(java.lang.Integer value) {
		this.value = value;
	}

	public java.lang.Boolean getExistsInAccount() {
		return this.existsInAccount;
	}

	public void setExistsInAccount(java.lang.Boolean existsInAccount) {
		this.existsInAccount = existsInAccount;
	}

	public java.lang.Boolean getExistsInLog() {
		return this.existsInLog;
	}

	public void setExistsInLog(java.lang.Boolean existsInLog) {
		this.existsInLog = existsInLog;
	}

	public java.lang.Boolean getMatchesValue() {
		return this.matchesValue;
	}

	public void setMatchesValue(java.lang.Boolean matchesValue) {
		this.matchesValue = matchesValue;
	}

	public java.lang.String getOutboundQueue() {
		return this.outboundQueue;
	}

	public void setOutboundQueue(java.lang.String outboundQueue) {
		this.outboundQueue = outboundQueue;
	}

	public java.lang.Integer getValueInAccount() {
		return this.valueInAccount;
	}

	public void setValueInAccount(java.lang.Integer valueInAccount) {
		this.valueInAccount = valueInAccount;
	}

	public java.lang.Integer getValueInLog() {
		return this.valueInLog;
	}

	public void setValueInLog(java.lang.Integer valueInLog) {
		this.valueInLog = valueInLog;
	}

	public Transaction(java.lang.String type, java.lang.Integer value,
			java.lang.Boolean existsInAccount, java.lang.Boolean existsInLog,
			java.lang.Boolean matchesValue, java.lang.String outboundQueue,
			java.lang.Integer valueInAccount, java.lang.Integer valueInLog) {
		this.type = type;
		this.value = value;
		this.existsInAccount = existsInAccount;
		this.existsInLog = existsInLog;
		this.matchesValue = matchesValue;
		this.outboundQueue = outboundQueue;
		this.valueInAccount = valueInAccount;
		this.valueInLog = valueInLog;
	}

}